### ISSUE TITLE
Something isn't working quite right

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/conversational-agent-application-starter-kit#13]
About every other message gives me the error `The conversation_id specified either does not exist or is invalid for the id`:

![screen shot 2016-02-24 at 5 56 09 pm](https://cloud.githubusercontent.com/assets/114976/13303927/f9eb4b2e-db1f-11e5-8f9b-a5f9014575fa.png)

**Comment by leandrodvd** [comment]
same thing here...

**Comment by germanattanasio** [comment]
This is not a problem in this sample application.

According to the dialog team:

> There have been intermittent connection issues with SQLDB that I believe is causing this issue. The problem is that at times it can throw off the entire conversation. We are working on it.
