### ISSUE TITLE
mock data not presented when running app locally

### ISSUE THREAD

**Issue by mrkrumhausen** [watson-developer-cloud/conversational-agent-application-starter-kit#14]
Dialog outputs "Cannot read property 'map' of undefined" instead of mock data.

<img width="720" alt="screen shot 2016-03-10 at 21 21 28" src="https://cloud.githubusercontent.com/assets/2011006/13694070/5bb8d0dc-e706-11e5-8d49-78324f7325e5.png">

**Comment by germanattanasio** [comment]
Make sure that when you are running it locally you don't have the TMDB key as an environment variable see [this](https://github.com/watson-developer-cloud/conversational-agent-application-starter-kit/blob/master/api/services.js#L52)

**Comment by germanattanasio** [comment]
The mock data is [here](https://github.com/watson-developer-cloud/conversational-agent-application-starter-kit/blob/master/api/moviedb-mock.js#L51)

**Comment by mrkrumhausen** [comment]
yes, thank you. It worked when I removed the placeholder text in the .env file
