### ISSUE TITLE
Broken link to movies api resource

### ISSUE THREAD

**Issue by renault-andres** [watson-developer-cloud/conversational-agent-application-starter-kit#15]
Hi, this might not be an issue itself but I think it is crucial for testing. The link in step 9 in the readme is currently broken.

Is there any workaround?

thanks!

**Comment by germanattanasio** [comment]
Are you talking about  "*Sign up at themoviedb.com and get an API key.*"?

**Comment by renault-andres** [comment]
Yes, may I have done something wrong? @germanattanasio
